name: Manual Nuxt 3 SSG Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Pages (SSG)
        run: npm run generate

      - name: List Content of dist Folder
        run: |
          echo "Contents of dist folder:"
          ls -R dist
