name: Manual Nuxt 3 SSG Build and Deploy

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Generate Static Pages (SSG)
        run: npm run generate

      - name: List Content of dist Folder
        run: ls -R dist

      - name: Clean Old Files on VPS (Optional)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: 'rm -rf /home/projects/portfolio/*'

      - name: Deploy to VPS via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "dist/*"
          target: "/home/projects/portfolio"

      # - name: Restart NGINX (Optional)
      #   uses: appleboy/ssh-action@v0.1.7
      #   with:
      #     host: ${{ secrets.VPS_HOST }}
      #     username: ${{ secrets.VPS_USER }}
      #     password: ${{ secrets.VPS_PASSWORD }}
      #     script: 'sudo systemctl reload nginx'
